name: 'Prebuilt Package Release'
on:
  schedule:
    - cron: '* 0 * * *'
  workflow_dispatch: {}

jobs:
  build-and-collect:
    name: Build and Collect
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Setup requirements
        run: chmod +x ./Setup.sh && bash Setup.sh
      - name: Run Script
        run: python generate_required_dependencies.py --output WebGPU --force 1 --generate_cpp 1 --update_default 1
      - name: Move files
        run: mkdir WebGPU-Cpp && mv WebGPU WebGPU-Cpp && mv CMake WebGPU-Cpp
      - name: Retrieve current Date Time in Hongkong TimeZone
        shell: bash
        run: echo "START_TIME=$(TZ=":Asia/Hongkong" date -R|sed 's/.....$//')" >> $GITHUB_ENV
      - name: Zip Files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r WebGPU.zip WebGPU-Cpp
      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ github.sha }}
          tag_exists_error: false
          message: "Automatically release"
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.START_TIME }}
          tag_name: ${{ github.sha }}
          files: |
            WebGPU.zip