name: 'Prebuilt Package Release'
on:
  schedule:
    - cron: '* 0 * * *'
  workflow_dispatch: {}

jobs:
  build-and-collect:
    name: Build and Collect
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Setup requirements
        run: ./Setup.sh
      - name: Run Script
        run: python generate_required_dependencies.py --output WebGPU --force 1 --generate_cpp 1 --update_default 1
      - name: Move files
        run: mkdir WebGPU-Cpp && mv WebGPU WebGPU-Cpp && mv CMake WebGPU-Cpp
      - name: Create release
        uses: Roang-zero1/github-create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Collect Artifact
        uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: "WebGPU-Cpp/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}